"""add video and visualization tables

Revision ID: f1b7463d221d
Revises: 002_enable_rls
Create Date: 2026-09-07 22:44:46.215938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1b7463d221d'
down_revision: Union[str, None] = '002_enable_rls'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Supabase: 002_enable_rls turned RLS on for the original seven tables. New tables
# must match, or these four would be the only ones in the database without
# row-level security.
NEW_TABLES = ['videos', 'video_frames', 'video_flags', 'visualization_layers']


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('duration_sec', sa.Float(), nullable=False),
    sa.Column('fps', sa.Float(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('frame_count', sa.Integer(), nullable=False),
    sa.Column('codec', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], name=op.f('fk_videos_job_id_analysis_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_videos'))
    )
    op.create_index(op.f('ix_videos_created_at'), 'videos', ['created_at'], unique=False)
    op.create_index(op.f('ix_videos_job_id'), 'videos', ['job_id'], unique=False)
    op.create_table('visualization_layers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('layer_id', sa.String(length=64), nullable=False),
    sa.Column('layer_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('provenance', sa.String(length=32), nullable=False),
    sa.Column('source_model', sa.String(length=64), nullable=True),
    sa.Column('artifact_path', sa.String(length=512), nullable=False),
    sa.Column('legend_path', sa.String(length=512), nullable=True),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], name=op.f('fk_visualization_layers_job_id_analysis_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visualization_layers'))
    )
    op.create_index(op.f('ix_visualization_layers_job_id'), 'visualization_layers', ['job_id'], unique=False)
    op.create_index(op.f('ix_visualization_layers_layer_id'), 'visualization_layers', ['layer_id'], unique=False)
    op.create_table('video_flags',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('video_id', sa.String(length=64), nullable=False),
    sa.Column('flag_id', sa.String(length=64), nullable=False),
    sa.Column('start_timestamp', sa.Float(), nullable=False),
    sa.Column('end_timestamp', sa.Float(), nullable=False),
    sa.Column('start_frame', sa.Integer(), nullable=False),
    sa.Column('end_frame', sa.Integer(), nullable=False),
    sa.Column('peak_frame', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('event_score', sa.Float(), nullable=False),
    sa.Column('keyframe_path', sa.Text(), nullable=True),
    sa.Column('overlay_path', sa.Text(), nullable=True),
    sa.Column('mask_path', sa.Text(), nullable=True),
    sa.Column('box_2d', sa.JSON(), nullable=True),
    sa.Column('model_scores', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('fk_video_flags_video_id_videos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_video_flags'))
    )
    op.create_index(op.f('ix_video_flags_flag_id'), 'video_flags', ['flag_id'], unique=False)
    op.create_index(op.f('ix_video_flags_video_id'), 'video_flags', ['video_id'], unique=False)
    op.create_table('video_frames',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('video_id', sa.String(length=64), nullable=False),
    sa.Column('frame_index', sa.Integer(), nullable=False),
    sa.Column('timestamp_sec', sa.Float(), nullable=False),
    sa.Column('is_keyframe', sa.Boolean(), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('fk_video_frames_video_id_videos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_video_frames'))
    )
    op.create_index(op.f('ix_video_frames_video_id'), 'video_frames', ['video_id'], unique=False)
    _enable_rls()
    # ### end Alembic commands ###


def _enable_rls() -> None:
    for table in NEW_TABLES:
        op.execute(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY;')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_frames_video_id'), table_name='video_frames')
    op.drop_table('video_frames')
    op.drop_index(op.f('ix_video_flags_video_id'), table_name='video_flags')
    op.drop_index(op.f('ix_video_flags_flag_id'), table_name='video_flags')
    op.drop_table('video_flags')
    op.drop_index(op.f('ix_visualization_layers_layer_id'), table_name='visualization_layers')
    op.drop_index(op.f('ix_visualization_layers_job_id'), table_name='visualization_layers')
    op.drop_table('visualization_layers')
    op.drop_index(op.f('ix_videos_job_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_created_at'), table_name='videos')
    op.drop_table('videos')
    # ### end Alembic commands ###
